@hostname = localhost
@port = 3000
@host = http://{{hostname}}:{{port}}/api

###  1. Registro
POST {{host}}/user/register
Content-Type: application/json

{
  "email": "user6@example.com",
  "password": "password123",
  "name": "Lino",
  "lastName": "Vives",
  "nif": "12345678X"
}

### 2. Validación

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Y2Y2MDc2MGRkZmUzMzM0MWExMWVkOCIsImlhdCI6MTc3NTE5ODMyNywiZXhwIjoxNzc1MTk5MjI3fQ.S9cPmXVmKaLw7Iv8Pxn4wVxW6LatwDvgp7S-EcabYMs
@codigo = 331938

PUT {{host}}/user/validation
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "code": "{{codigo}}"
}

### 3. Login
POST {{host}}/user/login
Content-Type: application/json

{
  "email": "user6@example.com",
  "password": "password123"
}

### 4A. Onboarding
@login_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWNmNjA3NjBkZGZlMzMzNDFhMTFlZDgiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzUxOTg0NzgsImV4cCI6MTc3NTE5OTM3OH0.DqJD6XcyXyhowQooorfgXzQsD3c6JnLt5xPIHrKP3XE
PUT {{host}}/user/register
Authorization: Bearer {{login_token}}
Content-Type: application/json

{
  "name": "Lino Modificado",
  "lastName": "Vives Actualizado",
  "nif": "87654321Z"
}

### 4B. Compañia
PATCH {{host}}/user/company
Authorization: Bearer {{login_token}}
Content-Type: application/json

{
  "name": "Nueva Empresa S.L.",
  "cif": "B99999999",
  "address": {
    "city": "Castellón"
  },
  "isFreelance": false
}

### 5. Subir logo
PATCH {{host}}/user/logo
Authorization: Bearer {{login_token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="logo"; filename="test-logo.png"
Content-Type: image/png

< ./uploads/test-logo.png
--boundary--

### 6. Obtener perfil completo
GET {{host}}/user
Authorization: Bearer {{login_token}}

### 7A. Refresh Token
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWNjZWU3NWZjZTdkZjhkMzg2NDAyMGMiLCJpYXQiOjE3NzUxNDAwMzUsImV4cCI6MTc3NTc0NDgzNX0.Cp9B74z3EtTibPRoJoHxGAHCjudPUdf_7rSxkXrjE0w

POST {{host}}/user/refresh
Content-Type: application/json

{
  "refreshToken": "{{refresh_token}}"
}

### 7B. Logout
POST {{host}}/user/logout
Authorization: Bearer {{login_token}}
Content-Type: application/json

{
  "refreshToken": "{{refresh_token}}"
}

### 8A. Soft Delete
DELETE {{host}}/user?soft=true
Authorization: Bearer {{login_token}}

### 8B. Hard Delete 
DELETE {{host}}/user
Authorization: Bearer {{login_token}}

### 9. Cambiar contraseña
PUT {{host}}/user/password
Authorization: Bearer {{login_token}}
Content-Type: application/json

{
  "currentPassword": "nuevaPassword456",
  "newPassword": "nuevaPassword4567"
}

### 10. Invitar compañero
POST {{host}}/user/invite
Authorization: Bearer {{login_token}}
Content-Type: application/json

{
  "email": "companero1@example.com",
  "name": "Invitado",
  "lastName": "Invitado"
}