@hostname = localhost
@port = 3000
@host = http://{{hostname}}:{{port}}/api

###  1. Registro
# @name registro
POST {{host}}/user/register
Content-Type: application/json

{
  "email": "user91@example.com",
  "password": "password123",
  "name": "Lino",
  "lastName": "Vives",
  "nif": "12345678X"
}
### 
@registro_token = {{registro.response.body.data.accessToken}}

### 2. Validación

@codigo = 514294

PUT {{host}}/user/validation
Authorization: Bearer {{registro_token}}
Content-Type: application/json

{
  "code": "{{codigo}}"
}

### 3. Login
# @name login
POST {{host}}/user/login
Content-Type: application/json

{
  "email": "user91@example.com",
  "password": "password123"
}
###
@login_token = {{login.response.body.accessToken}}
@refresh_token = {{login.response.body.refreshToken}}

### 4A. Onboarding
PUT {{host}}/user/register
Authorization: Bearer {{login_token}}
Content-Type: application/json

{
  "name": "Lino Modificado",
  "lastName": "Vives Actualizado",
  "nif": "87654321Z"
}

### 4B. Compañia
PATCH {{host}}/user/company
Authorization: Bearer {{login_token}}
Content-Type: application/json

{
  "isFreelance": false,
  "name": "Nueva Empresa S.L.",
  "cif": "B99999999",
  "address": {
    "street": "Calle Mayor, 15",
    "city": "Castellón"
  }
}

### 5. Subir logo
PATCH {{host}}/user/logo
Authorization: Bearer {{login_token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="logo"; filename="test-logo.png"
Content-Type: image/png

< ./uploads/test-logo.png
--boundary--

### 6. Obtener perfil completo
GET {{host}}/user
Authorization: Bearer {{login_token}}

### 7A. Refresh Token

POST {{host}}/user/refresh
Content-Type: application/json

{
  "refreshToken": "{{refresh_token}}"
}

### 7B. Logout
POST {{host}}/user/logout
Authorization: Bearer {{login_token}}
Content-Type: application/json

{
  "refreshToken": "{{refresh_token}}"
}

### 8A. Soft Delete
DELETE {{host}}/user?soft=true
Authorization: Bearer {{login_token}}

### 8B. Hard Delete 
DELETE {{host}}/user
Authorization: Bearer {{login_token}}

### 9. Cambiar contraseña
PUT {{host}}/user/password
Authorization: Bearer {{login_token}}
Content-Type: application/json

{
  "currentPassword": "password123",
  "newPassword": "nuevaPassword4567"
}

### 10. Invitar compañero
POST {{host}}/user/invite
Authorization: Bearer {{login_token}}
Content-Type: application/json

{
  "email": "companero1123@example.com",
  "name": "Invitado",
  "lastName": "Invitado"
}

### Prueba punto extra: empresa sin nombre (Debe dar 400)
PATCH {{host}}/user/company
Authorization: Bearer {{login_token}}
Content-Type: application/json

{
  "isFreelance": false,
  "cif": "B12345678"
}